CustomerChurn:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: FAISEL\SQLEXPRESS
      port: 1433
      database: ChurnData
      schema: dbo
      windows_login: True
      trust_cert: True